image: python:3.10-slim

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - echo "Iniciando Build..."
          - pip install -r requirements.txt
          - python -m unittest discover
    - step:
        name: Build Docker Image
        script:
          - echo "Construindo a imagem Docker..."
          - docker build -t my-python-app .
    - step:
        name: Push Docker Image to Docker Hub
        script:
          - echo "Fazendo login no Docker Hub..."
          - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          - docker tag my-python-app "$DOCKER_HUB_USERNAME/my-python-app:latest"
          - docker push "$DOCKER_HUB_USERNAME/my-python-app:latest"
    - step:
        name: Deploy to Render
        script:
          - echo "Deploy configurado no Render. Atualize a imagem no serviço manualmente."
