name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install flask pytest

    - name: Run tests
      run: pytest app/tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      run: |
        curl -fsSL https://cli.render.com/install.sh | bash
        render services update your-service-name --env production
